name: Secure CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PASSWORD: ${{ secrets.MY_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Run App Securely
        run: |
          echo "Password is $PASSWORD"
          python app.py


      
